### ISSUE TITLE
Bad reformatting at some beginning 

### ISSUE THREAD

**Issue by pirelaurent** [millennIumAMbiguity/processing-formatter#3]
**Describe the bug**
Writing a code in Processing IDE, i go to VSC to reformat it and found a wrong result. 
In use:    
Visual Studio Code 1.52.1.    
Windows 10    

**Screenshots**
Source code (part) was :    
![Screen Shot 02-01-21 at 07 32 PM](https://user-images.githubusercontent.com/4208305/106502154-4cd00180-64c4-11eb-8642-d18e25f1b10f.PNG)
And after formatting : 
![Screen Shot 02-01-21 at 07 32 PM 001](https://user-images.githubusercontent.com/4208305/106502179-55283c80-64c4-11eb-91e0-5946b6a18180.PNG)
You can see the wrong floatxNew and floatyNew .

**Additional context**
Could be some stuff with spaces and tabs ?   

A try a better sample with several beginnings:    
![Screen Shot 02-01-21 at 07 41 PM](https://user-images.githubusercontent.com/4208305/106503220-a553ce80-64c5-11eb-9ed9-38f7c58106e7.PNG)
In notepad++ to see spaces: 
![Screen Shot 02-01-21 at 07 47 PM](https://user-images.githubusercontent.com/4208305/106503867-7be77280-64c6-11eb-8703-b7b57d54323a.PNG)
One line is ok, the other nok :    
![Screen Shot 02-01-21 at 07 41 PM 001](https://user-images.githubusercontent.com/4208305/106503244-adac0980-64c5-11eb-8e14-4b357500b6b2.PNG)

HTH

**Comment by millennIumAMbiguity** [comment]
**Hello @pirelaurent,** 
Before I look into this I just need to confirm a few things. 

**When you formated, did you perform the format action one or several times?** 
When doing a lot of formatting you might have to format it multiple times in order to get the correct spacing. (This is especially true when working with tabs.)

**Did you use spaces or tabs?** 
The mode for spaces works a bit better than tabs. If you wish to switch from one to the other you simply can do that by changing the following settings:
`editor.detectIndentation` -> `true`
`editor.insertSpaces` -> `true` or `false` depending on what setting you looking for.

//_Hope to see your reply soon._
